[package]
name = "Messager"
version = "1.0.0"
authors = []

[addresses]
chaos = "0x13"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
